export const pricingData = [
  {
    duration: "30-Day",
    price: "51",
    isPopular: false,
    features: [
      "2,300+ Practice Questions",
      "500+ NGN Questions",
      "High Yield Review Videos",
      "Adaptive CAT Practice Tests",
      "Digital Flash Cards",
      "Dynamic Study Planner",
      "2 Self Assesment Test (1-2)*",
    ],
  },
  {
    duration: "60-Day",
    price: "42",
    isPopular: true,
    features: [
      "2,300+ Practice Questions",
      "500+ NGN Questions",
      "High Yield Review Videos",
      "Adaptive CAT Practice Tests",
      "Digital Flash Cards",
      "1 Self Assesment Test*",
    ],
  },
  {
    duration: "90-Day",
    price: "60",
    isPopular: false,
    features: [
      "2,300+ Practice Questions",
      "500+ NGN Questions",
      "High Yield Review Videos",
      "Adaptive CAT Practice Tests",
      "Digital Flash Cards",
      "Dynamic Study Planner",
      "3 Self Assesment Test (1-3)*",
    ],
  },
  {
    duration: "180-Day",
    price: "99",
    isPopular: false,
    features: [
      "2,300+ Practice Questions",
      "500+ NGN Questions",
      "High Yield Review Videos",
      "Adaptive CAT Practice Tests",
      "Digital Flash Cards",
      "Dynamic Study Planner",
      "4 Self Assesment Test (1-4)*",
      "One Time reset Option",
    ],
  },
  {
    duration: "360-Day",
    price: "117",
    isPopular: false,
    features: [
      "2,300+ Practice Questions",
      "500+ NGN Questions",
      "High Yield Review Videos",
      "Adaptive CAT Practice Tests",
      "Digital Flash Cards",
      "Dynamic Study Planner",
      "6 Self Assesment Test (1-6)*",
      "One Time reset Option",
    ],
  },
  {
    duration: "720-Day",
    price: "135",
    isPopular: false,
    features: [
      "2,300+ Practice Questions",
      "500+ NGN Questions",
      "High Yield Review Videos",
      "Adaptive CAT Practice Tests",
      "Digital Flash Cards",
      "Dynamic Study Planner",
      "8 Self Assesment Test (1-8)*",
      "One Time reset Option",
    ],
  },
];
